version: '3'

services:
  web: &default
    build:
      context: .
      dockerfile: Dockerfile.development
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - bundle:/bundle
    depends_on:
      - db
      - redis
    command: ./bin/start.sh
    environment:
      - REDIS_URL=redis://redis:6379
      - DATABASE_URL=postgres://postgres@db:5432

  sidekiq:
    <<: *default
    command: bundle exec sidekiq -C config/sidekiq.yml
    ports: []

  db:
    image: postgres:9.6
    volumes:
      - postgres:/var/lib/postgresql/data

  redis:
    image: redis:4.0.10

volumes:
  postgres:
  bundle:
